dist: xenial

language: go
go_import_path: istio.io/mixer

go:
  - 1.7.x

jdk:
  - oraclejdk8

env:
  - BAZEL_VERSION=0.4.2

addons:
  apt:
    packages:
      - wget

cache:
  directories:
    - $HOME/bazel/install
    - $HOME/bazel/outbase

before_install:
  - mkdir -p ${HOME}/bazel/install
  - cd ${HOME}/bazel/install
  - wget --no-clobber "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
  - chmod +x bazel_${BAZEL_VERSION}-linux-x86_64.deb
  - sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
  - cd ${TRAVIS_BUILD_DIR}
  - mv .bazelrc .bazelrc.orig
  - cat .bazelrc.travis .bazelrc.orig > .bazelrc

script:
  #- bazel  --output_base=${HOME}/bazel/outbase build @com_github_istio_api//:mixer/api/v1
  #- bazel  --output_base=${HOME}/bazel/outbase build //...
  #- bazel --output_base=${HOME}/bazel/outbase test //...
  - bazel build //...
  - bin/bazel_to_go.py
  - ls -l .
  - ls -l ${TRAVIS_BUILD_DIR}

abc:
  - bin/preplinters.sh
  - bin/runlinters.sh
  - go get  golang.org/x/net/http2
  - go get  golang.org/x/net/context
  - go test -v ./pkg/... ./cmd/... ./adapter/...

notifications:
  slack: istio-dev:wEEEbaabdP5ieCgDOFetA9nX
