steps:
- name: gcr.io/cloud-builders/bazel
  args: ['run', '//docker:mixer']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'istio/docker:mixer', 'gcr.io/$PROJECT_ID/mixer:$BUILD_ID']
images:
- 'gcr.io/$PROJECT_ID/mixer:$BUILD_ID'
